### ISSUE TITLE
图标经常加载不出来

### ISSUE THREAD

**Issue by netPeople110** [Pluto-Y/iOS-Echarts#10]
下载项目默认什么都不动直接运行，图表是可以加载出来的，但是我在echarts-all.js文件添加了个alert弹框后，弹框和图表都不出来了，后来我删了alert的代码再运行项目图表还是不出来，后来我新建了个项目把把iOS-Echarts文件夹拉到新项目中，并删除了JS文件夹的引用，添加了create floder references引用，然后在故事板拉了个webview并将属性custom class修改为了PYChartsView，然后调用了Demo中K线图的 showCandlestickDemo1，loadEcharts方法结果图表也出来，是否我的布置缺少什么步骤？

**Comment by Pluto-Y** [comment]
不懂你的问题所在，你是要问为什么加了alert之后不显示么？还有是图标还是图表？

**Comment by netPeople110** [comment]
我的意思是项目源码不改动的情况下图表可以正常显示，但是稍微改一下代码或把项目添加到新建的项目里时，原本应该显示图表的地方，一片空白

**Comment by Pluto-Y** [comment]
你的项目是含中文名的吗？

**Comment by netPeople110** [comment]
刚看了下，项目和路径都没有包含中文

**Comment by Pluto-Y** [comment]
能贴一下你的代码吗？

**Comment by netPeople110** [comment]
1，我复制到iOS-Echarts，RMMapper两个文件夹到新项目
2，我在新项目中向storyboard拉了个webview并修改custom class为PYEchartsView
3，JS添加create floder references
4，在头文件引用了"PYEchartsView.h"，"RMMapper.h"，"PYOption.h","PYAxis.h","PYLegend.h""PYCartesianSeries.h"
4，复制了DEMO中的K线图的showCandlestickDemo1
5，在viewDidLoad中调用[self showCandlestickDemo1];
    [_chartView loadEcharts];不知是否有错漏操作

**Comment by netPeople110** [comment]
对了，漏说了一步，我将storyboard中的webview 指向控制器头文件的@property (weak, nonatomic) IBOutlet PYEchartsView *chartView;属性

**Comment by Pluto-Y** [comment]
理论上应该没有太大问题。正常流程就是这样子。你查看一下`PYEchartsView`里面的`initAll`里面的NSURL *url的执行结果是不是为nil，先确认一下这个。

**Comment by netPeople110** [comment]
刚调试了一下，url只有值的

**Comment by Pluto-Y** [comment]
那后台调试试着输出一下Option，看看。

**Comment by netPeople110** [comment]
打印结果为<PYOption: 0x7fd2f1416c00>

**Comment by netPeople110** [comment]
\<PYOption: 0x7fd2f1416c00>\

**Comment by Pluto-Y** [comment]
这样我就不是很清楚了，你整体步骤是没什么问题的。

**Comment by Pluto-Y** [comment]
我试了一下是没有问题的，所以你要是实在没有解决的话，就在微博上联系我吧，我这里看看怎么帮你处理一下。

**Comment by netPeople110** [comment]
好的，我再研究一下，不行再请教你

**Comment by Pluto-Y** [comment]
好的。
