### ISSUE TITLE
X轴 会被吃掉一个 如图

### ISSUE THREAD

**Issue by TickYZH** [Pluto-Y/iOS-Echarts#11]
![3e4ef54b-a296-4b28-9ace-cbbe45266561](https://cloud.githubusercontent.com/assets/18656113/14778243/6c9040e4-0b04-11e6-8520-19545633ec93.png)

**Comment by TickYZH** [comment]
4月应该有30日  ，凡是30日的 最后一个都不会显示

**Comment by Pluto-Y** [comment]
最后一个数据没显示出来还是数据就是0啊？你先让所有X轴坐标都显示出来试试

**Comment by TickYZH** [comment]
数据是有的， 就是30日， 你看图上最后一列网格，与其他的网格宽度不同， 我试过设置宽度什么的还是没有用

**Comment by Pluto-Y** [comment]
我给你一个属性，你先设置这个属性看看30号的数据是否正确出现先。

**Comment by Pluto-Y** [comment]
用一下`PYAxis`里面的`PYAxisLabel`的`interval`这个属性设置成0试试看。

**Comment by TickYZH** [comment]
是这样吗     xAxis.axisLabel.interval = @0; 变成这样了
![59caa8e7-305c-464f-8cd0-d65d36c363a2](https://cloud.githubusercontent.com/assets/18656113/14809037/d9f16362-0bbc-11e6-9274-6da37e5f93a6.png)

**Comment by Pluto-Y** [comment]
可以看到图上是有30日的数据的，也就是说30号的数据是没有被吃掉，只是没有显示出来而已。

**Comment by TickYZH** [comment]
嗯嗯 那为什么会变成这样啊

**Comment by Pluto-Y** [comment]
看看这个配置你进行配置一下。
![image](https://cloud.githubusercontent.com/assets/10654142/14810647/7f56a7b4-0bc6-11e6-9810-bce82721e7aa.png)
