### ISSUE TITLE
chart的使用

### ISSUE THREAD

**Issue by wangbo593599657** [Pluto-Y/iOS-Echarts#12]
你好  我在使用echart的时候   生成json怎么快速处理呢

**Comment by wangbo593599657** [comment]
还有个问题就是，点击饼状图的时候  有个show显示“数据来源和百分比”  感觉有问题 总是会切2次

**Comment by Pluto-Y** [comment]
你点击的是在旁边的情况吧，就是原本显示的东西会超出界面的情况

**Comment by Pluto-Y** [comment]
至于你的第一个问题没有太明白，什么叫做生成json怎么快速处理呢

**Comment by wangbo593599657** [comment]
我的意思是 你现在给出的demo是直接一个字符串  我想json为动态生成的

**Comment by wangbo593599657** [comment]
就是点击饼状图的某一块的时候  会飘出数据来源和百分比对吧？但是飘出的时候 有点问题  总是飘了2次 感觉体验效果不佳  你下载demo试试呢

**Comment by Pluto-Y** [comment]
一般如果出现在旁边的情况下都会出现两次，你说的飘出来的情况是echart库自带就会有这个问题。这个问题之前就有人反馈过了，目前暂时没有办法解决。

**Comment by Pluto-Y** [comment]
至于你说的json动态生成是想说你先获得一个你想要样式的图表的json么？然后不会每次都变吧，一般一个App也就2-3种样式的图吧？

**Comment by wangbo593599657** [comment]
对的 我想动态添加图标的series序列

**Comment by wangbo593599657** [comment]
你好 方便说下你QQ吗  我迁入到项目中图出来不到  不知道怎么回事

**Comment by Pluto-Y** [comment]
微博上那个admin92055是你吗？

**Comment by wangbo593599657** [comment]
是的

**Comment by wangbo593599657** [comment]
可以QQ说嘛 这个回复太慢了  593599657

**Comment by hy451176411** [comment]
我的也出不来，自己引入就是出不来

**Comment by hy451176411** [comment]
QQ：451176411
