### ISSUE TITLE
使用cocoapods加载的iOS-Echarts,发现在PYEchartsView.h里使用[NSBundle mainBundle]访问不到echarts.html

### ISSUE THREAD

**Issue by WYZKirk** [Pluto-Y/iOS-Echarts#13]
使用cocoapods加载的iOS-Echarts,发现在PYEchartsView.h里使用[NSBundle mainBundle]访问不到echarts.html,PYEchartsView.h里的代码如下:NSBundle *echartsBundle = [NSBundle mainBundle];NSString *urlString = [echartsBundle pathForResource:@"echarts" ofType:@"html"];
运行时发现urlString为空,不知道是我加载时错误还是少添加什么东西.

**Comment by Pluto-Y** [comment]
项目中包含中文么？或者特殊字符。

**Comment by WYZKirk** [comment]
没我把;NSString *urlString = [echartsBundle pathForResource:@"echarts" ofType:@"html"]改成NSString *urlString = [echartsBundle pathForResource:@"Frameworks/iOS_Echarts.framework/echarts" ofType:@"html"];然后可以用了...

**Comment by WYZKirk** [comment]
没,我把NSString *urlString = [echartsBundle pathForResource:@"echarts" ofType:@"html"]改成NSString *urlString = [echartsBundle pathForResource:@"Frameworks/iOS_Echarts.framework/echarts" ofType:@"html"];然后可以用了...

**Comment by hai3343** [comment]
这个问题我也遇到了希望能修复一下。
