### ISSUE TITLE
多表图加载问题

### ISSUE THREAD

**Issue by linfeizhang** [Pluto-Y/iOS-Echarts#15]
界面刚出现时就只有一个cell中的表格显现出来了，其他的不显示，滑动使cell进入缓存池在下拉或返回再进入界面就会加载了，这是什么原因？
![qq20160825-1 2x](https://cloud.githubusercontent.com/assets/17806686/17959362/6e284b9e-6ad2-11e6-9d95-4e0fcc0ec930.png
[echart-demo.zip](https://github.com/Pluto-Y/iOS-Echarts/files/436325/echart-demo.zip)
)

**Comment by Pluto-Y** [comment]
没看到图片。

**Comment by linfeizhang** [comment]
![Uploading QQ20160825-1@2x.png…]()

**Comment by linfeizhang** [comment]
![qq20160825-1 2x](https://cloud.githubusercontent.com/assets/17806686/17964819/88e8134a-6aed-11e6-8f78-31e9247fccbc.png)
[echart-demo.zip](https://github.com/Pluto-Y/iOS-Echarts/files/436645/echart-demo.zip)

**Comment by naihetxi** [comment]
因为共用一个html，所以只有数据加载的时间不一样才会出现两个图表，换成真实数据就没有这个问题了！
