### ISSUE TITLE
拖入swift项目中，编译报错

### ISSUE THREAD

**Issue by mrsensen** [Pluto-Y/iOS-Echarts#19]
如图。。求怎么解决
<img width="330" alt="qq20160917-0 2x" src="https://cloud.githubusercontent.com/assets/12557001/18606200/1a4e9bd4-7cdb-11e6-979b-7feb32b3b23f.png">

**Comment by mrsensen** [comment]
@xypng 谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢！！！！ 加到预编译里面就没问题了。跪地答谢！！ 请接收我这个小白的感谢

**Comment by Pluto-Y** [comment]
@xypng 感谢
