### ISSUE TITLE
项目加载后，图表部分显示空白？

### ISSUE THREAD

**Issue by mrsensen** [Pluto-Y/iOS-Echarts#20]
如题！但是鼠标点击空白处移动的话 控制台会有坐标提示，js目录是通过create floder references方式添加的。求帮助

**Comment by Pluto-Y** [comment]
@mrsensen 后台除了输出坐标提示前，还有别的提示吗？

**Comment by mrsensen** [comment]
@Pluto-Y 谢谢  已经解决了 嘿嘿！我用的swift3 有些地方可能没写对。后来我直接看的您写的实例，重新写了一遍就可以了😄
