### ISSUE TITLE
swift调用时，没有block初始化方法，该怎么调用呢？

### ISSUE THREAD

**Issue by mrsensen** [Pluto-Y/iOS-Echarts#21]
如题如图 🙄

<img width="681" alt="1" src="https://cloud.githubusercontent.com/assets/12557001/18713739/f872aa5a-8045-11e6-8fef-c0df78128e29.png">

**Comment by Pluto-Y** [comment]
暂时好像无解，不过之后会弄一个Swift版本

**Comment by mrsensen** [comment]
@Pluto-Y 好的！期待Swift
