### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by WenWu92** [Pluto-Y/iOS-Echarts#24]
你好，谢谢你的分享，说个事，我点击图形时，出形的提示会弹跳两下,希望能改一下，对了，随道 问一下，你那是否还需要人力，如果要的话，我可以贡献我的热诚

**Comment by Pluto-Y** [comment]
那个弹两次还真不是我理所能力的，我试了下echarts本身就是弹两次，这个如果要改得echarts的javascript进行修改，至于那个人力的话，你可以加QQ群，然后添加我为好友，我们再讨论一下
