### ISSUE TITLE
导入iOS－ECharts后，import “PYEchartsView.h”调试保错

### ISSUE THREAD

**Issue by lb1254353678** [Pluto-Y/iOS-Echarts#26]
1./Users/goodbaby/Documents/xcode_workspace/GBSmartManufacture_TC/Pods/Headers/Public/iOS-Echarts/PYEchartsView.h:73:40: No type or protocol named 'PY_WEB_DELEGATE'

2./Users/goodbaby/Documents/xcode_workspace/GBSmartManufacture_TC/Pods/Headers/Public/iOS-Echarts/PYEchartsView.h:73:28: Cannot find interface declaration for 'PY_WEB_VIEW', superclass of 'PYEchartsView'

3./Users/goodbaby/Documents/xcode_workspace/GBSmartManufacture_TC/Pods/Headers/Public/iOS-Echarts/PYEchartsView.h:77:31: Unknown type name 'PY_EDGE_INSET'

4./Users/goodbaby/Documents/xcode_workspace/GBSmartManufacture_TC/Pods/Headers/Public/iOS-Echarts/PYEchartsView.h:154:84: Unknown type name 'PY_IMAGE'

**Comment by Pluto-Y** [comment]
http://www.jianshu.com/p/0e638bedb612
