### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by lypcliuli** [Pluto-Y/iOS-Echarts#27]
1、我使用pods下载下来之后 ，里面没iOS-Echarts.h这个文件，#import "iOS-Echarts.h"之后找不到头文件；2、直接下载demo拷贝demo里面的iOS-charts这个文件（已经把js路径里的文件变成蓝色文件夹了），编译报错，错是PYColor交叉引用，但是并没有改动里面的东西。
以上问题期待优化，谢谢。

**Comment by Pluto-Y** [comment]
需要添加一下预编译
http://www.jianshu.com/p/0e638bedb612
