### ISSUE TITLE
添加数据问题

### ISSUE THREAD

**Issue by linfeizhang** [Pluto-Y/iOS-Echarts#28]
series.data = @"(function () {var d = [];var len = 0;var now = new Date();var value;while (len++ < 150) {d.push([new Date(2014, 9, 1, 0, len*100),(Math.random()*30).toFixed(2) - 0,(Math.random()*100).toFixed(2) - 0]);}return d;})()";

这是不等距折线图的加载数据，这是demo给的方法，可是我做的是ios项目，我获得是（时间,数值）的数组，如何能把这个数据添加到图标中啊？这series.data 后面跟的js啊，我的数据是对象数组啊？怎么转换带入啊，不会啊，求解啊？最好能写个小demo给我看看，谢谢！

**Comment by Pluto-Y** [comment]
不对吧，你这个是js的代码是（*，时间）的形式吧，具体的你只要把x轴的数据放在xAxis的data里面，然后把y轴的数据放在series.data里面即可，你可以用oc或者swift代码生成之后直接填充到里面即可
