### ISSUE TITLE
为什么我通过pod iOS-Echarts 安装了组件过去，引入头文件缺找不到？

### ISSUE THREAD

**Issue by Thomas1987** [Pluto-Y/iOS-Echarts#29]
在需要的地方引入 iOS-Echarts.h 就可以了，可是我引入却报找不到该头文件，我是通过pod ‘iOS-Echarts’ 
安装的！！

**Comment by Thomas1987** [comment]
PYZoomEchartsView.h 这个头文件也找不到！是不是简书里面的文章都是很早以前写的了 ？？？

**Comment by Pluto-Y** [comment]
@Thomas1987 我不知道你看的是哪篇简书里面的文章，不过你应该只要添加一下预编译即可。
http://www.jianshu.com/p/0e638bedb612

**Comment by Thomas1987** [comment]
我发现问题了：我通过pod 方式安装的 iOS-Echarts 里面缺少了几个目录，View目录没有，所以这几个引用都找不到！！ 我看的文章地址是，http://www.jianshu.com/p/3d5fe1f4693d

**Comment by Thomas1987** [comment]
通过pod安装的文件和直接通过源码下载的为什么会不一样呢？
