### ISSUE TITLE
关于坐标文本间距 PYInterval 的问题。

### ISSUE THREAD

**Issue by changelee82** [Pluto-Y/iOS-Echarts#33]
使用  PYIntervalAll  结果x轴坐标只显示第一个项目的文本，
我试着把 PYIntervalAll  = @"all"; 
改成 PYIntervalAll  = @"0"; 
就可以显示全部项目了，是否是我哪里弄错了？

**Comment by Pluto-Y** [comment]
@changelee82 解决了吗？

**Comment by changelee82** [comment]
解决了，感谢！
