### ISSUE TITLE
雷达图怎么设置数据为倒序显示

### ISSUE THREAD

**Issue by hjqiaho** [Pluto-Y/iOS-Echarts#34]
就是0在最外层  把100等大的值显示里面 越大显示越靠中心  如果取负值的话 可以有这效果但点击的提示也是负的

**Comment by Pluto-Y** [comment]
@hjqiaho 你可以显示的时候通过formatter来进行调整

**Comment by hjqiaho** [comment]
@Pluto-Y   是像这样吗 具体formatter的值怎么写呢
    NSMutableDictionary *trigger = [NSMutableDictionary dictionary];
    [trigger setObject:@"axis" forKey:@"trigger"];
    [trigger setObject:@"{b}<br/>{a0}:{c0}" forKey:@"formatter"];
    
    NSDictionary *radar = @{
                            @"legend":legend,
                            @"polar":polararray,
                            @"series":seriesarray,
                            @"tooltip":trigger,
                            @"title":[NSDictionary dictionaryWithObject:@"各科能力雷达图" forKey:@"text"]

**Comment by Pluto-Y** [comment]
你用的是哪一个版本你的iOS-Echarts，你用radar来设置option吗？还是怎么样？能贴一些关于你option的代码吗

**Comment by hjqiaho** [comment]
NSArray *templist = list[@"list"];
    NSMutableArray *indicatortemp = [NSMutableArray array];
    NSMutableArray *radarvalue = [NSMutableArray array];
    for (int i = 0; i<templist.count; i++) {
        NSDictionary *tempblank = @{@"max":@(-10),@"min":@(0),@"text":templist[i][@"blankName"]};
        NSInteger rank = [[NSString stringWithFormat:@"%@",templist[i][@"rank"]] integerValue];
        [indicatortemp addObject:tempblank];
        [radarvalue addObject:@(-rank)];
    }
    NSArray *legenddata = @[@"学科排名"];
    NSDictionary *legend = [NSDictionary dictionaryWithObjectsAndKeys:@"vertical",@"orient",@"right",@"x",@"bottom",@"y",legenddata,@"data",nil];
    NSArray *polararray = @[ @{@"radius": @"80%",@"indicator":indicatortemp,@"scale":@(YES)},];
    NSArray *seriesarray = @[@{@"name": @"各学科排名",@"sort":@"descending",@"type": @"radar",@"data":@[
                                       @{@"name":@"学科排名",
                                         @"value":radarvalue}
                                       ]}
                             ];
    NSMutableDictionary *trigger = [NSMutableDictionary dictionary];
    [trigger setObject:@"axis" forKey:@"trigger"];
    [trigger setObject:@"{b}<br/>{c}:{c0}" forKey:@"formatter"];
    
    NSDictionary *radar = @{
                            @"legend":legend,
                            @"polar":polararray,
                            @"series":seriesarray,
                            @"tooltip":trigger,
                            @"title":[NSDictionary dictionaryWithObject:@"各科能力雷达图" forKey:@"text"]
                            
                            };
    PYOption *option = [RMMapper objectWithClass:[PYOption class] fromDictionary:radar];
    [_kEchartView setOption:option];
    [_kEchartView loadEcharts];


就是这段代码 版本就是前几天在这个git下载的

**Comment by hjqiaho** [comment]
NSArray *templist = list[@"list"];
    NSMutableArray *indicatortemp = [NSMutableArray array];
    NSMutableArray *radarvalue = [NSMutableArray array];
    for (int i = 0; i<templist.count; i++) {
        NSDictionary *tempblank = @{@"max":@(-10),@"min":@(0),@"text":templist[i][@"blankName"]};
        NSInteger rank = [[NSString stringWithFormat:@"%@",templist[i][@"rank"]] integerValue];
        [indicatortemp addObject:tempblank];
        [radarvalue addObject:@(-rank)];
    }
    NSArray *legenddata = @[@"学科排名"];
    NSDictionary *legend = [NSDictionary dictionaryWithObjectsAndKeys:@"vertical",@"orient",@"right",@"x",@"bottom",@"y",legenddata,@"data",nil];
    NSArray *polararray = @[ @{@"radius": @"80%",@"indicator":indicatortemp,@"scale":@(YES)},];
    NSArray *seriesarray = @[@{@"name": @"各学科排名",@"sort":@"descending",@"type": @"radar",@"data":@[
                                       @{@"name":@"学科排名",
                                         @"value":radarvalue}
                                       ]}
                             ];
    NSMutableDictionary *trigger = [NSMutableDictionary dictionary];
    [trigger setObject:@"axis" forKey:@"trigger"];
    [trigger setObject:@"{b}<br/>{c}:{c0}" forKey:@"formatter"];
    
    NSDictionary *radar = @{
                            @"legend":legend,
                            @"polar":polararray,
                            @"series":seriesarray,
                            @"tooltip":trigger,
                            @"title":[NSDictionary dictionaryWithObject:@"各科能力雷达图" forKey:@"text"]
                            
                            };
    PYOption *option = [RMMapper objectWithClass:[PYOption class] fromDictionary:radar];
    [_kEchartView setOption:option];
    [_kEchartView loadEcharts];


就是这段代码 版本就是前几天在这个git下载的

**Comment by hjqiaho** [comment]
NSArray *templist = list[@"list"];
    NSMutableArray *indicatortemp = [NSMutableArray array];
    NSMutableArray *radarvalue = [NSMutableArray array];
    for (int i = 0; i<templist.count; i++) {
        NSDictionary *tempblank = @{@"max":@(-10),@"min":@(0),@"text":templist[i][@"blankName"]};
        NSInteger rank = [[NSString stringWithFormat:@"%@",templist[i][@"rank"]] integerValue];
        [indicatortemp addObject:tempblank];
        [radarvalue addObject:@(-rank)];
    }
    NSArray *legenddata = @[@"学科排名"];
    NSDictionary *legend = [NSDictionary dictionaryWithObjectsAndKeys:@"vertical",@"orient",@"right",@"x",@"bottom",@"y",legenddata,@"data",nil];
    NSArray *polararray = @[ @{@"radius": @"80%",@"indicator":indicatortemp,@"scale":@(YES)},];
    NSArray *seriesarray = @[@{@"name": @"各学科排名",@"sort":@"descending",@"type": @"radar",@"data":@[
                                       @{@"name":@"学科排名",
                                         @"value":radarvalue}
                                       ]}
                             ];
    NSMutableDictionary *trigger = [NSMutableDictionary dictionary];
    [trigger setObject:@"axis" forKey:@"trigger"];
    [trigger setObject:@"{b}<br/>{c}:{c0}" forKey:@"formatter"];
    
    NSDictionary *radar = @{
                            @"legend":legend,
                            @"polar":polararray,
                            @"series":seriesarray,
                            @"tooltip":trigger,
                            @"title":[NSDictionary dictionaryWithObject:@"各科能力雷达图" forKey:@"text"]
                            
                            };
    PYOption *option = [RMMapper objectWithClass:[PYOption class] fromDictionary:radar];
    [_kEchartView setOption:option];
    [_kEchartView loadEcharts];

就是这段代码 版本就是前几天在这个git下载的

**Comment by Pluto-Y** [comment]
@hjqiaho 可以修改这下面的，应该是c0或者c前面加一个负号试试，建议使用原声属性来进行设置，你这种方式如果设置了多余的属性是不会有提示的，具体的demo看github上的demo
```
[trigger setObject:@"{b}{c}:{c0}" forKey:@"formatter"];
```

**Comment by hjqiaho** [comment]
加上负号就不返回数值或文字了 直接显示 {-c} 
有没有直接倒序显示的方法？

**Comment by hjqiaho** [comment]
[label setObject:@"(function(params) {return -params.value;})" forKey:@"formatter"];


这么写解决了
