### ISSUE TITLE
网格怎么设置透明，或者不显示？

### ISSUE THREAD

**Issue by Steve-Leo** [Pluto-Y/iOS-Echarts#35]
我有一个图标，给的格式里面是没有网格的，现在好像默认都有网格，我把网格的borderColor 也不管用。

**Comment by Pluto-Y** [comment]
@Steve-Leo 具体可以看这里的参数
http://echarts.baidu.com/echarts2/doc/doc.html#Grid

**Comment by Steve-Leo** [comment]
好的，谢谢

**Comment by Steve-Leo** [comment]
通过设置x轴和y轴的axis.splitLine.show = NO; 可以不显示。。
