### ISSUE TITLE
把webview替换成wkwebview 页面很小需要双击放大 

### ISSUE THREAD

**Issue by ntncever** [Pluto-Y/iOS-Echarts#39]
把webview替换成wkwebview 页面很小需要双击放大

**Comment by Pluto-Y** [comment]
@ntncever 你说的这个是你的修改，bug不属于这个库，而且元旦过后WKWebView的应该也能上了，所以如果你要用WKWebView的话可以等元旦后更新库即可。

**Comment by Pluto-Y** [comment]
@ntncever 你可以使用1.4.1的版本里面封装了WKWebView的封装了，用WKEchartsView替代原来的PYEchartsView即可
