### ISSUE TITLE
 [_kEchartView setOption:option]抛出异常 表示没有这个方法

### ISSUE THREAD

**Issue by lin493369** [Pluto-Y/iOS-Echarts#4]

**Comment by Pluto-Y** [comment]
有吧，你去查看一下PYEchartsView这个类里面

**Comment by lin493369** [comment]
可以找到这个方法，但在运行时就提示 -[UIWebView setOption:]: unrecognized selector sent to instance 0x17571fd0

**Comment by Pluto-Y** [comment]
哦。你用的是UIWebView，你是在Xib里面用的吧。

**Comment by lin493369** [comment]
是的 用XIB 请问问题可能出在哪里

**Comment by lin493369** [comment]
哦哦 我知道了。。

**Comment by Pluto-Y** [comment]
你在Xib里面没有指定他的类型为PYEchartsView吧

**Comment by lin493369** [comment]
恩 是的 感谢 提醒我了

**Comment by Pluto-Y** [comment]
没事。
