### ISSUE TITLE
[PYEchartsView refreshEcharts] 不起作用

### ISSUE THREAD

**Issue by nimitz871016** [Pluto-Y/iOS-Echarts#40]
我需要更新数据。于是我获取option，并添加数据。我选择的是折线图。
option.series[0].addData(@"20");
option.xAxis[0].addData(@"周一");//同时我也新增了x轴
最后我调用
[chartsView refreshEcharts];
什么都没改变。
但是如果我调用
[chartsView loadEcharts];
可以看到改变的效果。
但是这会刷新所有的数据。像这个https://segmentfault.com/q/1010000005054630 的问题一样。
请问刷新数据的正确姿势。

ps：js文件似乎很久没有更新了，是否需要更新？我在echarts官网上，发现不需要更新x轴，也可以达到添加数据的效果。（demo中，如果只添加数据，不添加x轴，则也不会更新）

**Comment by Pluto-Y** [comment]
@nimitz871016 
* 第一点，调用 `refreshEchart` 只会回到初始化的 `option` 的状态，正确的调用方式应该是`refreshEchartsWithOption:`的方法
* 第二点，调用 `loadEcharts` 会导致重新渲染echarts的的图表
* 第三点，您说的这个是echarts3，这个库封装的是echarts2
* 第四点，如果替换js的话，会导致module层很多都需要替换，目前没有打算替换这块，不过最近正在用 Swift 分装 echarts 3.0

**Comment by nimitz871016** [comment]
赞
