### ISSUE TITLE
折线图里面很多UI图标都叠在一起了

### ISSUE THREAD

**Issue by amovexu** [Pluto-Y/iOS-Echarts#42]
点折线图，标准折线图，就可以看到

**Comment by Pluto-Y** [comment]
@amovexu Demo里面的代码都是官网的代码，之所以没有去处理，就是希望大家可以看OC代码的同事能对照官网的来进行对比。

**Comment by amovexu** [comment]
改了一下，现在可以用了  谢谢 @Pluto-Y

**Comment by Pluto-Y** [comment]
@amovexu 不用谢，能用就好~
