### ISSUE TITLE
折线图，断开的点如何传值

### ISSUE THREAD

**Issue by nimitz871016** [Pluto-Y/iOS-Echarts#45]
在折线图中，要表示无值的点，要传递什么？

我在做一个实时更新的折线图，数据是不断的添加的。在添加过程中会遇到某些点数据是无，但是仍然要在图中有所表示。

比如data:[11, 11, 15, , 30, 13, 10], 15和30之间少了一个值，最后图像在15和30间空出一个位置，并不做连线。

在iOS中，要传递什么值？我试了下[NSNull null]，会导致bug，后面的数据全部变成不连线了。

**Comment by Pluto-Y** [comment]
@nimitz871016  可以传递一个@"-"试试

**Comment by nimitz871016** [comment]
已解决。3q
