### ISSUE TITLE
Swift 的导入

### ISSUE THREAD

**Issue by wjssxc** [Pluto-Y/iOS-Echarts#46]
swift 导入会报各种错误，是什么问题 ？

**Comment by Pluto-Y** [comment]
@wjssxc 正在封装Swift版本的，不过是基于Echarts 3.0的

**Comment by Pluto-Y** [comment]
@wjssxc 正在封装Swift版本的，不过是基于Echarts 3.0的

**Comment by wjssxc** [comment]
大概多久能够会有？我们正在考虑从之前的iOS-charts 转用 Echarts

**Comment by Pluto-Y** [comment]
现在已经封装了一部分了，目前应该折线图应该是ok了，你还需要用到哪些图，我可以优先考虑，如果正好是常用的几个的话
