### ISSUE TITLE
Label的formatter问题

### ISSUE THREAD

**Issue by yanglei19871122** [Pluto-Y/iOS-Echarts#57]
label的formatter 如果用function写 如何赋值啊 label.formatter = @"(function(params){function checkLabel(){strs.push(str.substring(0,6));str=str.substring(5,str.length);if(str.length>6){checkLabel()}else{strs.push(str)}}var str='';var strs=[];if(params&&params.name){str=params.name;checkLabel();return strs.join('\n')}})" 打印出来 整个function前后都带有双引号，如果把双引号去掉，function可以生效，但是如何去掉啊

**Comment by Pluto-Y** [comment]
@yanglei19871122 不用去掉，直接可以带双引号就可以了，js那边写了方法会进行转换的
