### ISSUE TITLE
请问怎么添加直角折线

### ISSUE THREAD

**Issue by limeihui1127** [Pluto-Y/iOS-Echarts#60]
我在echarts文档中看见了直角折线图，但是不明白怎么添加，求大神解答

**Comment by Pluto-Y** [comment]
看github上的demo就可以了，你下载下来运行看看

**Comment by limeihui1127** [comment]
谢谢您的回答，不过我看了一下demo，用的是echarts2.0，我看Echarts3.0有直角折线，所以我改了一下js，测试了一下，我用的几个图表没什么问题。再次感谢您的分享。

**Comment by limeihui1127** [comment]
请问怎么适配屏幕翻转呢？

**Comment by Pluto-Y** [comment]
不懂你说的适配是什么意思，整个界面的适配应该跟这个视图里面的实现应该是没关系的，应该还是看你如何设置这个View的高宽

**Comment by limeihui1127** [comment]
屏幕翻转的时候图表不会随着view变化而变化，我需要怎么设置呢？
