### ISSUE TITLE
dataZoom滑动后定位的起始位置和终点位置的值怎么获取

### ISSUE THREAD

**Issue by naihetxi** [Pluto-Y/iOS-Echarts#7]

**Comment by Pluto-Y** [comment]
你说的是PYZoomEchartsView这个类拓展视图吗？

**Comment by naihetxi** [comment]
//数据区缩放
        option.dataZoom = [[PYDataZoom alloc] init];
        option.dataZoom.show = YES;
        option.dataZoom.realtime = YES; 是堆积面积图这个试图 dataZoom移动后 起始位置和终点位置会弹出一个值

**Comment by Pluto-Y** [comment]
哦哦，这个的话，可以通过通过对Event进行监控后获得。具体的话可以通过`PYEchartsView`里面的`addHandlerForAction:withBlock:`的方式来进行监控DATA_ZOOM的事件。

**Comment by naihetxi** [comment]
我试试，谢谢啦！

**Comment by Pluto-Y** [comment]
好哒，记得帮我宣传一下哟！<(￣▽￣)> 哇哈哈…

**Comment by naihetxi** [comment]
好的，你这个库真的很不错的，就是还有好多没有封装呀！你这个库是一直更新吗

**Comment by Pluto-Y** [comment]
我空闲的时候就会更新。昨天刚封装了一个有缩放和拖拉手势的子视图，不过只是初步封装。

**Comment by naihetxi** [comment]
pod上去没有addHandlerForAction:withBlock:这个方法吧！而且我按照你那个Demo加上去后，我发现- (BOOL)webView:(UIWebView *)webView shouldStartLoadWithRequest:navigationType:这个方法第一次加载的时候走了，加载完成后单独滑动dataZoom的滑动条，图形变化了， 但是这个方法不会调用，我怎么样才能拿到那个startVaule 和endValue这两个值呢

**Comment by Pluto-Y** [comment]
要不然我更新一下pod上的吧？太久没更新了。

**Comment by Pluto-Y** [comment]
@naihetxi 能说下加下QQ吗？

**Comment by naihetxi** [comment]
290379226
