### ISSUE TITLE
关于resizeDiv的问题

### ISSUE THREAD

**Issue by liubin303** [Pluto-Y/iOS-Echarts#71]
- 需求：一个TableView中包含多个Chart,涉及cell复用的问题，每个Chart的grid不一样。

- 现象：当我在复用方法中要重置chartView的大小时调用了resizeDiv方法，但是没有起效。还是使用的复用的cell里chart的size。

- 问题：最终定位到PYEchartsView中的resizeDiv方法。发现逻辑上好像有点问题，不知道是我理解有问题还是作者写错了。

`
/**
 *  Resize the main div in the `echarts.html`
 */
- (void)resizeDiv {
    float height = self.frame.size.height;
    float width = self.frame.size.width;
    if (!CGSizeEqualToSize(_divSize, CGSizeZero)) {
        height = _divSize.height;
        width = _divSize.width;
    }
    else {
        _divSize = CGSizeMake(width, height);
    }
    NSString *divSizeCss = [NSString stringWithFormat:@"'height:%.0fpx;width:%.0fpx;'", height, width];
    NSString *js = [NSString stringWithFormat:@"%@(%@)", @"resizeDiv", divSizeCss];
    [self stringByEvaluatingJavaScriptFromString:js];
}
`

我觉得应该是原来的divsize与新的chartview size不相等时才需要更新_divsize,且传递给js的宽高要用chartview size，即方法中的height，width，才能让chart刷新成你想要的frame。针对上面方法改动就是如果新的size与原_divSize不相等则重新赋值。

**Comment by liubin303** [comment]
`
- (void)resizeDiv {
    float height = self.frame.size.height;
    float width = self.frame.size.width;
    if (!CGSizeEqualToSize(_divSize, CGSizeZero)) {
//        height = _divSize.height;
//        width = _divSize.width;
        _divSize = CGSizeMake(width, height);
    }
//    else {
//        _divSize = CGSizeMake(width, height);
//    }
    NSString *divSizeCss = [NSString stringWithFormat:@"'height:%.0fpx;width:%.0fpx;'", height, width];
    NSString *js = [NSString stringWithFormat:@"%@(%@)", @"resizeDiv", divSizeCss];
    [self stringByEvaluatingJavaScriptFromString:js];
}
`
最终修改成这样问题解决

**Comment by Pluto-Y** [comment]
* 首先div的大小并不等于grid的大小，如果你要改变grid的大小，直接调整grid的大小即可
* 其次你只调用resizeDiv的大小是不起作用的，正确的应该是调用完resizeDiv之后再重新刷新Echarts的图表，即loadEcharts，绘制Echarts会根据最后一个div的大小重新绘制，而你只resizeDiv并不会导致loadEcharts之前记录的div大小发生变化
* 最后div大小并不等于chartsview的大小，可能会比chartsview的大小还大，div的大小有点类似于chartsview里面一个展现图表的layer的大小

**Comment by liubin303** [comment]
- div的大小应该就是承载chart的webview大小，如果不调整div大小而只调整grid的大小会出现grid被遮挡或者没有自适应cell高度的问题，因为你的div还是复用的cell的大小。

- 在resizeDiv当然也重新设置了option以及loadEcharts，这个是在cell里面做的。

我这个代码经过MVVM的封装，可能看起来跟原始的不一样，但是应该能看懂，就是我有很多个这样的cell，每个cell对chart大小的要求不一样。
`
@implementation GYEChartCellModel

- (instancetype)initWithDefault{
    self = [super initWithDefault];
    if (self) {
        self.cellClass = [GYEChartCell class];
        self.selectionStyle = UITableViewCellSelectionStyleNone;
        self.hiddenSeparateLine = YES;
        self.hiddenRightArrow = YES;
        self.normalBackgroundColor = COLOR_SYSTEM_CLEAR;
    }
    return self;
}

@end

@interface GYEChartCell ()

@property (nonatomic, strong) GYEChartCellModel *cellModel;
@property (nonatomic, strong) PYEchartsView *chartView;

@end

@implementation GYEChartCell

- (void)cellDidLoad{
    [super cellDidLoad];
    self.backgroundColor = COLOR_SYSTEM_CLEAR;
    [self.contentView addSubview:self.chartView];
    
    [self.chartView mas_makeConstraints:^(MASConstraintMaker *make) {
        make.edges.equalTo(UIEdgeInsetsZero);
    }];
}

- (void)setObject:(id<FMCellModelBasicProtocol>)object{
    [super setObject:object];
    self.cellModel = object;
    
    [self.chartView resizeDiv];
    [self.chartView setOption:self.cellModel.option];
    [self.chartView loadEcharts];
}

- (PYEchartsView *)chartView{
    if (_chartView == nil){
        _chartView = [[PYEchartsView alloc] init];
    }
    return _chartView;
}

@end
`

**Comment by liubin303** [comment]
不纠结这些需求，我们聚焦现在resizeDiv这个方法本身的逻辑，应该是违背你本意的吧。
我修改了一下  你看看
`
/**
 *  Resize the main div in the `echarts.html`
 */
- (void)resizeDiv {
    float height = self.frame.size.height;
    float width = self.frame.size.width;
    if (!CGSizeEqualToSize(_divSize, CGSizeZero)) {
//        height = _divSize.height;
//        width = _divSize.width;
        _divSize = CGSizeMake(width, height);
    }
//    else {
//        _divSize = CGSizeMake(width, height);
//    }
    NSString *divSizeCss = [NSString stringWithFormat:@"'height:%.0fpx;width:%.0fpx;'", height, width];
    NSString *js = [NSString stringWithFormat:@"%@(%@)", @"resizeDiv", divSizeCss];
    [self stringByEvaluatingJavaScriptFromString:js];
}
`
