### ISSUE TITLE
WKWebView 渲染问题  导致图表不显示

### ISSUE THREAD

**Issue by jinlongzhu** [Pluto-Y/iOS-Echarts#76]
最近发现用tableViewCell 嵌入 图表有的会显示不出来，网上查了下是WKWebView渲染的问题只需要加入
    [webView setNeedsLayout];
这段代码就可以了！但是我们的WkWebView 的父类ScrollView 现在是不可滚动的转态 无法触发渲染此方法！问下有有好的处理方法避免图表不显示问题

**Comment by jinlongzhu** [comment]
解决！这个是WkView的 问题我在cell里面加了个监听tableView滚动然后echartView 调用 setNeedsLayout就OK了

**Comment by Pluto-Y** [comment]
@jinlongzhu 厉害了
