### ISSUE TITLE
饼状图设置label的position为inner label不显示了

### ISSUE THREAD

**Issue by ligui-iOS** [Pluto-Y/iOS-Echarts#79]
饼状图设置label的position为inner label不显示了

**Comment by Pluto-Y** [comment]
可以贴出代码或者贴出图来看看吗？

**Comment by ligui-iOS** [comment]
饼图: 当label position为inner时有效，为label位置到圆心的距离与圆半径(环状图为内外半径和)的比例系数，默认为0.5。

找到原因了
