### ISSUE TITLE
Echart

### ISSUE THREAD

**Issue by flyMan1991** [Pluto-Y/iOS-Echarts#9]
折线图,我如何获取我点击时的X的位置

**Comment by Pluto-Y** [comment]
X轴的位置？是指Echart上X轴的数值还是，PYEchartView上的的位置？

**Comment by flyMan1991** [comment]
X 轴的数值

**Comment by flyMan1991** [comment]
请问一下,xAxis.axisLabel文本能不能旋转方向,我们要做的是可以旋转方向的

**Comment by Pluto-Y** [comment]
@flyMan1991 如果是X轴的数值的话，通过回调函数是可以拿得到的吧？

**Comment by Pluto-Y** [comment]
@flyMan1991 可以旋转的，官方文档里面有提供旋转的功能。

**Comment by flyMan1991** [comment]
你的API中没有提供方法,并且你封装成的OC方法中没有关于旋转的属性和方法,X轴的值,我没有找到回调函数

**Comment by Pluto-Y** [comment]
你用的是哪个版本？

**Comment by flyMan1991** [comment]
去年12月份下载的

**Comment by Pluto-Y** [comment]
我今天晚上应该会再更新一个版本，你方面急吗？我可以先告诉你用法。

**Comment by flyMan1991** [comment]
我的项目不急,我明天在更新一下,另外echart可以缩放吗

**Comment by Pluto-Y** [comment]
可以的，在PYZoomEchartsView里面提供了直角系的缩放，你可以去看看符合要求不。

**Comment by flyMan1991** [comment]
等你今天更新完之后,我在操作,现在不是很急

**Comment by Pluto-Y** [comment]
好，我晚上更新完通知你一声。至于PYZoomEchartsView你可以试试看。

**Comment by flyMan1991** [comment]
好的,谢谢了

**Comment by Pluto-Y** [comment]
已经更新到1.1.6了，你可要更新一下，选择的话，可要用`PYAxisLabel`里面的`rotate`这个属性。
